name = "sur"
description = "Unified theme for the Southern California Nix User Group"
license = "MIT"
homepage = "https://socal-nug.com/"
min_version = "0.15.0"
demo = "https://socal-nug.com/"

[extra]

[author]
name = "Southern California Nix User Group Organizers"
homepage = "https://socal-nug.com/"